# Generated by Django 4.1.3 on 2022-12-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarToon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('popularity', models.IntegerField()),
                ('director', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'CarToon',
            },
        ),
    ]
