# Generated by Django 4.1.3 on 2022-12-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0002_cartoon_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='img_link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
