# Generated by Django 4.1.3 on 2022-12-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_link', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('evaluation', models.CharField(max_length=10)),
                ('date', models.DateField(max_length=10)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
