# Generated by Django 4.1.3 on 2022-12-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('img_link', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
