# Generated by Django 4.1.3 on 2022-12-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
