# Generated by Django 4.1.4 on 2022-12-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_info_product_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
